name: Zequez
markdown: redcarpet
highlighter: true
permalink: /:year/:month/:day/:title
default_lang: es
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
assets:
  js_compressor:  uglifier
  css_compressor: sass
  debug: true
image:
  source: uploads
  output: uploads
  presets:
    right:
      attr:
        class: image-right
      width: 350
    left:
      attr:
        class: image-left
      width: 350
    right-small:
      attr:
        class: image-right-small
      width: 233
    left-small:
      attr:
        class: image-left-small
      width: 233
    center:
      attr:
        class: image-center
      width: 700