source 'https://rubygems.org'

gem 'mini_magick'
gem 'sass'
gem 'uglifier'
gem 'coffee-script'
gem 'jekyll', '~> 1.5'
gem 'jekyll-assets'
gem 'jekyll-localization'
# gem 'jekyll-i18n', '1.0.2'
gem 'i18n'